### PR TITLE
Vitalium: Notify host of changed parameters on patch load.

### LINKED ISSUE #96: LV2 Vitalium settings do not restore correctly when a project is saved and reopened
This is supposedly a known issue regarding the fork of JUCE that Vitalium's LV2 version uses. In the DAWs I have used (Ardour and Zrythm), projects with Vitalium LV2 instances will often have those instances altered when the projects are reopened. The settings of some instances are randomly changed, ruining the patches. The only way to deal with this is to use the VST3 plugin (which is laggier in Zrythm and more prone to crashing in Ardour), or to manually save every instance as its own patch before closing a project and set them back to those patches when reopening the project. I do not know what conditions are required for this issue to manifest, but I have found other people who have experienced it. I am using the plugin on Arch Linux through the distrho-ports Arch package.

### PR DESCRIPTION
**Pull request by DarkRTA**
This fixes #96 as far as I am aware.

### CODE REVIEW

**Comment by xard-dev** [comment]
I tested the nightly build and can confirm that this pull request solved the issue #96 I was experiencing with various software.

**Comment by falkTX** [comment]
logic looks good to me, but the syntax is very odd.
please change

`auto old_values = std::map<std::string, float>();` to just `std::map<std::string, float> old_values;`
  
and `for (auto i = controls_.begin(); i != controls_.end(); i++) {` to `for (const auto& it : controls_) {`

thanks!

**Comment by DarkRTA** [comment]
I am currently out on vacation and won't be able to fix this for a few days.

**Comment by DarkRTA** [comment]
this should be good now. found some downtime to go ahead and do this

**Comment by falkTX** [comment]
thanks! will merge now then

**Pull request merged**
