### PR TITLE
Vitalium: Use SVG Logo

### LINKED ISSUE #103: Better rendering of Vitalium's logo
Currently it looks quite rough when it's displayed in Vitalium's window:
vitalium_logo_current
perhaps some anti-aliasing is needed?

### PR DESCRIPTION
**Pull request by DarkRTA**
This replaces the `.png` currently in use with a hand drawn `.svg`. The `.svg` was produced by auto-tracing the logo in Inkscape, followed by manually cleaning it up.

The code was done by reverting the commit which introduced the `.png` in the first place, and cleaning up anything that was broken by doing so.

Closes #103.

### CODE REVIEW

**Comment by falkTX** [comment]
does that mean the logo gets colorized too?

I sadly dont have automated tests in place, cant check here yet if the build is all ok.
So will do some testing only later next week.

**Comment by DarkRTA** [comment]
> does that mean the logo gets colorized too?

It does. Themes can now override it too.

**Comment by falkTX** [comment]
nice, super cool! thanks for the effort!

will try to give this some attention next week.

**Comment by DarkRTA** [comment]
@falkTX is there any chance you can get around to reviewing this one soon.

**Comment by DarkRTA** [comment]
Will this ever get reviewed? Its been a few months now.

**Comment by falkTX** [comment]
give it time. life happens and people get busy.

I thought I would be able to handle vitalium stuff in March/April, but sadly it is going to need some time.
I update this repo to use JUCE 6.1 instead of 6.0.
Thing is, while Vitalium works in JUCE 6.0 it looks totally wrong in JUCE 6.1.
So very likely i will need to take vitalium from the DISTRHO-Ports project and make it a standalone project, or try to fix the graphical issues myself.
Matt, the original Vital author, has ignored my questions for why things got broken, so we are on our own for figuring this out.

I will come back to this eventually

**Comment by Nyabinary** [comment]
@falkTX Would be awesome to see Vitalium become it's own project with it own presets etc.

**Comment by falkTX** [comment]
nice to rebase against latest master, please do it again :) I did not notice GH actions were only set for commits, not PRs

**Comment by falkTX** [comment]
Alright now everything is in place, and no build issues at least.

I decided to keep vitalium in distrho-ports, if that was not obvious yet. Since JUCE has breaking changes regularly, it is best for us to keep compat with each minor version anyway, as that will make it easier to (im)port other plugins.

**Comment by falkTX** [comment]
and of course, thanks!

**Comment by DarkRTA** [comment]
Took almost a year but im glad it finally made it in. :)

**Comment by falkTX** [comment]
It still needs a release, but now the automated builds help in the mean time.

**Comment by unfa** [comment]
@DarkRTA Thanks for recreating the vectors!

**Pull request merged**
